#!/bin/bash

set -e

cp -r static/* $OUTPUT_ARTIFACTS_DIR/

function build_resume {
    TYPENAME="$1"

    echo "Building $TYPENAME resume..."
    mkdir -p "$OUTPUT_ARTIFACTS_DIR/resume/$TYPENAME"
    cp -r resume/* "$OUTPUT_ARTIFACTS_DIR/resume/$TYPENAME"
    (cd "$OUTPUT_ARTIFACTS_DIR/resume/$TYPENAME" && ./render-template.py "$TYPENAME" resume.tex.jinja "$QBT_ENV_REVISION" > resume.tex && pdflatex resume.tex)
}

# TODO: version control python, jinja, etc?
# fetch jinja2 template engine
VE="$OUTPUT_ARTIFACTS_DIR/.ve"
python --version
virtualenv -p $(which python) "$VE"
source "$VE/bin/activate"
pip install jinja2

build_resume short
build_resume long

# cleanup virtuanenv so it isn't part of artifacts
rm -rf "$VE"

# create timestamp file for last modified date - this isn't reproducible, by design, oh well =(
echo "<p>Last Built On: $(date)</p>" > "$OUTPUT_ARTIFACTS_DIR/timestamp.txt"

# rename/reposition the resumes so they are in the correct path
mv "$OUTPUT_ARTIFACTS_DIR/resume/short/resume.tex" "$OUTPUT_ARTIFACTS_DIR/resume/resume-short.tex"
mv "$OUTPUT_ARTIFACTS_DIR/resume/short/resume.pdf" "$OUTPUT_ARTIFACTS_DIR/resume/resume-short.pdf"
mv "$OUTPUT_ARTIFACTS_DIR/resume/long/resume.tex" "$OUTPUT_ARTIFACTS_DIR/resume/resume-full.tex"
mv "$OUTPUT_ARTIFACTS_DIR/resume/long/resume.pdf" "$OUTPUT_ARTIFACTS_DIR/resume/resume-full.pdf"
rm -rf "$OUTPUT_ARTIFACTS_DIR/resume/long"
rm -rf "$OUTPUT_ARTIFACTS_DIR/resume/short"

